// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type Item struct {
	ID        int32
	Available int32
	Name      string
	Vender    string
	UnitPrice int32
}

type Order struct {
	ID         int32
	OrderBy    int32
	Items      []int32
	TotalPrice int32
	Discount   float64
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
	Discount float64
}
